stages:
  train:
    cmd: python main.py fit --config ./config/mnist.yaml
    deps:
      - ./config/train_mnist.yaml
      - main.py
    outs:
      - ./logs/model.ckpt:
          cache: true
          desc: "Final model checkpoint"
          type: model
      - ./logs/model.onnx:
          cache: true
          desc: "Exported onnx model"
          type: model
      - ./logs/model.onnx.data:
          cache: true
          desc: "Lightning onnx param file"
  test:
    cmd: python main.py test --config ./config/train_mnist.yaml --ckpt_path ./logs/model.ckpt
    deps:
      - ./config/train_mnist.yaml
      - main.py
    outs:
      - ./logs/metrics.json:
          cache: true
          desc: "Validation metrics file"
metrics:
  - ./logs/metrics.json
