[tool.poetry]
name = "lightning-template"
version = "0.1.0"
readme = "README.md"
packages = [{ include = "src", from = "." }]

[tool.poetry.dependencies]
python = ">=3.13,<3.15"
torch = ">=2.10.0,<3.0.0"
codecarbon = "^3.2.1"
comet-ml = "^3.55.0"
torchmetrics = "^1.8.2"
onnxruntime = "^1.23.2"
onnx = "^1.20.1"
dotenv = "^0.9.9"
omegaconf = "^2.3.0"
lightning = "^2.6.0"
jsonargparse = {extras = ["signatures"], version = "^4.45.0"}
torchio = "^0.21.2"
litdata = "^0.2.60"
matplotlib = "^3.10.8"
dvc = "^3.66.1"
gto = "^1.9.0"
pytest = "^9.0.2"
onnxscript = "^0.6.0"
dvc-s3 = "^3.3.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
