seed_everything: true
trainer:
  max_epochs: 1
  precision: 32-true
  callbacks:
    - class_path: lightning.pytorch.callbacks.RichProgressBar
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      dict_kwargs:
        monitor: val_loss
        mode: min
        save_top_k: 1
        filename: "model"
        dirpath: ./logs
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5
        mode: min
    - class_path: src.callbacks.codecarbon.CodeCarbonCallback
      init_args:
        project_name: "kmc-model-qc"
        save_to_file: False
        log_level: error
        experiment_name: ${data.class_path}_${model.class_path}_${timestamp:%Y%m%d_%H%M%S}
    - class_path: src.callbacks.export.ONNXExportCallback
      dict_kwargs:
        output_dir: ./logs
        model_name: model
        verbose: True
    - class_path: src.callbacks.metrics.ExportMetricsCallback
      dict_kwargs:
        output_dir: ./logs
  logger:
    class_path: lightning.pytorch.loggers.CometLogger
    dict_kwargs:
      api_key: ${oc.env:COMET_API_KEY}
      workspace: ${oc.env:COMET_WORKSPACE}
      project: "kmc-model-qc"
      log_env_details: False
      online: False
      offline_directory: ./comet
      name: ${data.class_path}_${model.class_path}_${timestamp:%Y%m%d_%H%M%S}
model:
  class_path: DefaultNN
  init_args:
    in_channels: 1
    out_channels: 10
    criterion:
      class_path: torch.nn.CrossEntropyLoss
      init_args:
        reduction: mean
data:
  class_path: MNISTDataModule
  init_args:
    data_dir: ./data
    batch_size: 32
    num_workers: 4

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001 
    weight_decay: 0.05

lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.1